apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: kube-burner-test
spec:
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
