apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterloader2-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps", "batch", "extensions"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterloader2-binding
subjects:
  - kind: ServiceAccount
    name: testkube-api-server-tests-job
    namespace: testkube
roleRef:
  kind: ClusterRole
  name: clusterloader2-role
  apiGroup: rbac.authorization.k8s.io
