apiVersion: v1
kind: Pod
metadata:
  generateName: pod-
  labels:
    app: kube-burner-test
spec:
  containers:
  - name: pause
    image: busybox:1.36
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
